name: Deploy to GitHub Pages (gh-pages branch)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install Docusaurus dependencies
      run: cd docusaurus && npm ci
      
    - name: Build React app
      run: npm run build:react
      
    - name: Build Docusaurus
      run: npm run build:docusaurus
      
    - name: Copy blog files
      run: npm run copy:blog
      
    - name: Deploy to gh-pages branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        publish_branch: gh-pages
